site_name: Giray Coskun
site_url: https://giraycoskun.dev/
site_author: Giray Coskun
site_description: I am a software engineer and this is my personal website

# Repository
repo_name: giraycoskun/giraycoskun.dev
repo_url: https://github.com/giraycoskun/giraycoskun.dev

theme:
  language: en 
  name: material
  custom_dir: overrides
  logo: assets/computer-science.png
  favicon: assets/computer-science.png
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - toc.follow
    - content.code.copy
  icon:
    tag:
      python: fontawesome/brands/python

  palette:
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/giraycoskun
    - icon: fontawesome/brands/github 
      link: https://github.com/giraycoskun
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/giraycoskun/
  tags:
    Python: python
  

plugins:
    - search
    - macros
    - blog:
        blog_toc: true
        pagination: true
        pagination_per_page: 5
    - tags:
        tags_file: ./blog/tags.md

markdown_extensions:
  - pymdownx.pathconverter:
      base_path: '' # default: ''
      relative_path: 'docs/' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

watch:
  - overrides

nav:
  - Home: index.md
  - Giray Coskun:
    - home/index.md
    - Education: home/education.md
    - Publications: home/publications.md 
    - Projects: home/projects.md
    - Experience: home/experience.md
    - Skills: home/skills.md
    - CV: home/cv.md
  - My Projects: 
    - projects/index.md
    - Research Projects: projects/research-projects.md
    - Cours Projects: projects/course-projects.md
    - Personal Side Projects: projects/side-projects.md
  - Developer's Notebook:
    - developers-notebook/index.md
    - developers-notebook/my-python-development-environment.md
    - developers-notebook/starting-python-project.md
    - developers-notebook/host-your-projects.md
    - developers-notebook/my-bookmarks.md
    # - developers-notebook/modern-cpp-development.md
    # - developers-notebook/self-hosted.md
    # - developers-notebook/async-python.md
    # - developers-notebook/java-in-macos.md
  - My Blog:
    - blog/index.md
    - blog/tags.md
