site_name: Giray Coskun
site_url: https://giraycoskun.dev/
site_author: Giray Coskun
site_description: I am a software engineer and this is my personal website

# Repository
#repo_name: giraycoskun/giraycoskun.dev
#repo_url: https://github.com/giraycoskun/giraycoskun.dev

theme:
  language: en 
  name: material
  custom_dir: overrides
  logo: assets/computer-science.png
  favicon: assets/computer-science.png
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - toc.follow

  palette:
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/giraycoskun
    - icon: fontawesome/brands/github 
      link: https://github.com/giraycoskun
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/giraycoskun/
  

plugins:
    - search
    - macros

markdown_extensions:
  - pymdownx.pathconverter:
      base_path: '' # default: ''
      relative_path: 'docs/' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Giray Coskun:
    - home/index.md
    - Education: home/education.md
    - Publications & Projects: home/projects.md
    - Experience: home/experience.md
    - Skills: home/skills.md
    - CV: home/cv.md
  - My Projects: 
    - projects/index.md
    - Research Projects: projects/research-projects.md
    - Coursework Projects: projects/course-projects.md
    - Side Projects: projects/side-projects.md
  - Developer's Notebook:
    - developers-notebook/index.md 
    - Starting a Python Project: developers-notebook/python-project.md
    - Dependency Management in Python: developers-notebook/dependency-management-python.md
    - Modern C++ Development: developers-notebook/modern-cpp-development.md
  - My Bookmarks:
    - Python: awesome-bookmarks/python.md
