name: ci 
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
    #----------------------------------------------
    #       Install uv
    #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --locked
      #----------------------------------------------
      # Build Site
      #----------------------------------------------
      - name: Build site
        run: |
          uv run mkdocs build --clean
      #----------------------------------------------
      # Deploy Site to Github Pages
      #----------------------------------------------
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          
